on: 
  push:
    branches:
     - master 



 




jobs: 
 build:
   runs-on: ubuntu-latest 

   steps:
     - uses: actions/checkout@v3

     - name: "login to docker" 
       run: docker login  --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_TOKEN }}
     
     - name:  "bulding to doker"
       run: docker build -t ${{ secrets.DOCKER_USERNAME }}/test3 .

     - name: "pushing"
       run: docker push ${{ secrets.DOCKER_USERNAME }}/test3


   
